### ISSUE TITLE
Self hosting issues

### ISSUE THREAD

**Issue by sedikitaja** [Librum-Reader/Librum-Server#29]
Hi folks,

**Disclaimer**: I'm still relatively new to the world of Docker and docker compose, so it's possible that I've missed something basic and therefor made some wrong assumptions.

I've spent an evening and a morning trying to set this up, however I have not yet been able to successfully set this up.

## Issue

Running the [provided docker-compose.yml](https://github.com/Librum-Reader/Librum-Server/blob/main/docker-compose.yml) results in an error  `[Warning] Access denied for user 'librum'@'172.29.0.3' (using password: YES)`.

After encountering this (and having experienced a similar one with Bookstack), I began implementing my own environmental variables to address this.

<details>
  <summary>docker-compose.yml</summary>

```yaml
---
version: "3.8"
services:
  librum:
    image: ghcr.io/librum-reader/librum-server:latest
    hostname: librum
    container_name: librum
    ports:
      - ${LIBRUM_PORTS}
    networks:
      - librum
    volumes:
      - ${LIBRUM_CONFIG_DIRECTORY}:/var/lib/librum-server/librum_storage
    environment:
      - JWTValidIssuer=exampleIssuer          # Optional. You can leave it as-is
      - JWTKey=exampleOfALongSecretToken      # Optional. You can leave it as-is
      - SMTPEndpoint=${LIBRUM_MAIL_SMTP}         # Example for Gmail: smtp.gmail.com:587
      - SMTPUsername=${LIBRUM_MAIL_USER}
      - SMTPPassword=${LIBRUM_MAIL_PASSWORD}
      - SMTPMailFrom=${LIBRUM_MAIL_EMAIL}
      - DBConnectionString=Server=mariadb;port=3306;Database=${LIBRUM_DB_NAME};Uid=${LIBRUM_DB_USER};Pwd=${LIBRUM_DB_PASSWORD};
      - AdminEmail=${LIBRUM_ADMIN_EMAIL}          # Admin login username
      - AdminPassword=${LIBRUM_ADMIN_PASSWORD}      # Admin login password
    restart: unless-stopped
    depends_on:
      librum_db:
        condition: service_healthy            # Ensures the DB is up before the server.

  librum_db:
    image: mariadb:latest
    hostname: mariadb
    container_name: librum_db
    networks:
      - librum
    volumes:
      - ${LIBRUM_DB_DIRECTORY}:/var/lib/mysql
    environment:
      - MARIADB_USER=${LIBRUM_DB_USER}
      - MARIADB_PASSWORD=${LIBRUM_DB_PASSWORD}
      - MARIADB_DATABASE=${LIBRUM_DB_NAME}
      - MARIADB_ROOT_PASSWORD=${LIBRUM_DB_PASSWORD}
    restart: unless-stopped
    healthcheck:                              # Ensures the DB is up before the server.
      test: ["CMD", "mariadb-admin", "ping", "-u", "${LIBRUM_DB_USER}", "-p${LIBRUM_DB_PASSWORD}", "-h", "localhost"]
      interval: 20s
      timeout: 40s
      retries: 3
      start_period: 30s

networks:
  librum:
    name: "librum"

volumes:
  librum:
    name: "librum"
  librum_db:
    name: "librum_db"
```
</details>

<details>
  <summary>.env</summary>

```.env
LIBRUM_ADMIN_EMAIL="sedikitaja@sedikitaja.com"
LIBRUM_ADMIN_PASSWORD="strongPassword123"
LIBRUM_CONFIG_DIRECTORY="config"
LIBRUM_DB_DIRECTORY="librum_db"
LIBRUM_DB_NAME="librum_database"
LIBRUM_DB_USER="librum_admin"
LIBRUM_DB_PASSWORD="superpassword"
LIBRUM_MAIL_EMAIL="mailuser123@example.com"
LIBRUM_MAIL_PASSWORD="smtpUserPassword123"
LIBRUM_MAIL_SMTP="smtp.sedikitaja.com"
LIBRUM_MAIL_USER="sedikitaja"
LIBRUM_PORTS="5010:5000" 
```
</details>

However, with this I bump into the error `Access to the path '/var/lib/librum-server/librum_storage/books' is denied`. 

I have tried the solution listed in [Issue 20](https://github.com/Librum-Reader/Librum-Server/issues/20) , which results in no errors from Docker, however, when trying to log into with Libram_Reader I am presented with `We're sorry. Logging you in failed, please try again later.`

I have set the `libram.conf` to point at the correct IP and port and enabled the `selfHosted=true`

When logging in with a user that does not exist, as expected, I receive the error `Your email or password is wrong`.

I could use a bit of a sanity check and/or guidance to get this up and running.
