### ISSUE TITLE
Docker install won't start with error "Access denied for user 'librum'@'localhost'"

### ISSUE THREAD

**Issue by goaliedude3919** [Librum-Reader/Librum-Server#37]
[docker-compose file](https://pastebin.com/iHSRrx0P)

[Logs](https://pastebin.com/9gh84Tc3)

**Comment by Lipown** [comment]
Same here :/

**Comment by benooye** [comment]
Wanted to give Librum a try, it looks very interesting, but same error here also

**Comment by abdessalaam** [comment]
I still have this issue.
I don't use kubernetes so I tried to implement @paulcsiki paulcsiki solution via vanilla docker compose, but to no avail...

``` 
# Init service to chmod the volume
  init-storage:
    image: busybox:latest
    command: sh -c "mkdir -p /vol-path && chmod -R 777 /vol-path"
    volumes:
      - data:/vol-path
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    restart: "no" 
```
